### ISSUE TITLE
What license has this font

### ISSUE THREAD

**Issue by ff6347** [los-gordos/BLOKK#2]
I love the project. With what kind of license do you distribute this?

**Comment by bqkode** [comment]
Hey @fabianmoronzirfas, WTFPL :)

But we'd appreciate a mention if you use it or make something cool with it 👍

**Comment by ff6347** [comment]
Cool. Thanks. BTW the download on your website is broken. https://blokkfont-losgordos.netdna-ssl.com/v2/BLOKKNeue-Regular.zip

**Comment by bqkode** [comment]
Thanks @fabianmoronzirfas, was some issues with the cdn provider zone. Should be fixed now :)
